print(Fore.LIGHTBLACK_EX + ' __    ____  ____  ____  ___  ____  _  _ ')
print(Fore.LIGHTWHITE_EX + '(  )  (_  _)( ___)(_  _)/ __)( ___)( \( )')
print(Fore.LIGHTBLACK_EX + ' )(__  _)(_  )__)   )( ( (_-. )__)  )  ( ')
print(Fore.LIGHTWHITE_EX + '(____)(____)(__)   (__) \___/(____)(_)\_)) Created by t.me/liftium')
time.sleep(0.5)
os.system('cls')


print(Fore.LIGHTBLACK_EX + ' __    ____  ____  ____  ___  ____  _  _ ')
print(Fore.LIGHTWHITE_EX + '(  )  (_  _)( ___)(_  _)/ __)( ___)( \( )')
print(Fore.LIGHTBLACK_EX + ' )(__  _)(_  )__)   )( ( (_-. )__)  )  ( ')
print(Fore.LIGHTWHITE_EX + '(____)(____)(__)   (__) \___/(____)(_)\_)) Created by t.me/liftium')
print('Currently disabled.')
time.sleep(5)
os.system('cls')